#!/bin/bash

# Remove certain default directories.
xdg-user-dirs-update --set DESKTOP "$HOME/"
xdg-user-dirs-update --set MUSIC "$HOME/"
xdg-user-dirs-update --set PUBLIC "$HOME/"
xdg-user-dirs-update --set TEMPLATES "$HOME"

# Set new locations for certain default directories.
xdg-user-dirs-update --set DOCUMENTS "$HOME/personal/dox"
xdg-user-dirs-update --set DOWNLOAD "$HOME/personal/dl"
xdg-user-dirs-update --set PICTURES "$HOME/personal/pix"
xdg-user-dirs-update --set VIDEOS "$HOME/personal/vid"

# Apply changes.
xdg-user-dirs-update --force
xdg-user-dirs-gtk-update --force
