#!bin/sh
# All .ttf files need to go under /usr/share/fonts/ or /usr/local/share/fonts/ somewhere, and run fc-cache as root.

# Installing Iosevka
curl -OL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Iosevka.tar.xz
echo ''
tar -xf Iosevka.tar.xz
echo ''
sudo mv *.ttf /usr/share/fonts/
sudo fc-cache
echo ''
rm -rf LICENSE.md readme.md README.md
