#!/bin/sh

echo "An interent connection is required when running this script."
echo "This script is desigend to be run from your home directory. Please put this script in your home directory before running."
echo " "

echo "Press [ENTER] key when ready to continue"
read y

# Give sudo privileges ahead of time, so that we hopefully only have to enter a password once.
echo " "
sudo -v

# Moving to home directory at the beginning of the process.
cd ~

# xdg-user-dirs.
mkdir ~/personal/dox
mkdir ~/personal/dl
mkdir ~/personal/pix
mkdir ~/personal/vid

xdg-user-dirs-update --set DESKTOP ~
xdg-user-dirs-update --set DOCUMENTS ~/personal/dox
xdg-user-dirs-update --set DOWNLOAD ~/personal/dl
xdg-user-dirs-update --set MUSIC ~
xdg-user-dirs-update --set PICTURES ~/personal/pix
xdg-user-dirs-update --set PUBLIC ~
xdg-user-dirs-update --set TEMPLATES ~
xdg-user-dirs-update --set VIDEOS ~/personal/vid

xdg-user-dirs-update
xdg-user-dirs-update --force
xdg-user-dirs-gtk-update
xdg-user-dirs-gtk-update --force

rm -rf Desktop
rm -rf Documents
rm -rf Downloads
rm -rf Music
rm -rf Pictures
rm -rf Public
rm -rf Templates
rm -rf Videos
echo " "

# System Update and Upgrade.
sudo apt update -y
sudo apt upgrade -y
sudo apt install --fix-missing -y
sudo apt upgrade --allow-downgrades -y
sudo apt full-upgrade --allow-downgrades -y
echo " "

# System Clean Up.
sudo apt install -f
sudo apt autoremove -y
sudo apt autoclean
sudo apt clean
echo " "

# Install APT packages.
sudo apt install -y \
git \
exa \
zsh \
mpv \
sxiv \
neovim \
newsboat \
alacritty \
zathura \

sudo apt update
sudo apt upgrade
echo " "

# Linking up dotfiles.
cd ~
cd personal
git clone --depth 1 https://github.com/Mvcvalli/.dotfiles.git
rm -rf ~/.config
ln -s ~/personal/.dotfiles/.config ~
ln -s ~/personal/.dotfiles/.zshenv ~
ln -s ~/personal/.dotfiles/.newsboat ~
ln -s ~/personal/.dotfiles/.gitconfig ~
cd ~
echo " "

# Installing vim-plug (for nvim).
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
echo " "

# Install nvim plugins
nvim -es -u init.vim -i NONE -c "PlugInstall" -c "qa"
echo " "

# Changing shell to zsh
sudo chsh -s $(which zsh)
zsh
echo " "

# Installing zap (zsh plugin manger)
zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1
echo " "

echo "Install complete!"
echo "Please restart your computer now"
