#!/bin/sh

echo "An interent connection is required when running this script."
echo "This script is desigend to be run from your home directory. Please put this script in your home directory before running."
echo " "

echo "Press [ENTER] key when ready to continue"
read y

# Give sudo privileges ahead of time, so that we hopefully only have to enter a password once.
echo " "
sudo -v

# System Update and Upgrade.
sudo apt update -y
sudo apt upgrade -y
sudo apt install --fix-missing -y
sudo apt upgrade --allow-downgrades -y
sudo apt full-upgrade --allow-downgrades -y
echo " "

# System Clean Up.
sudo apt install -f
sudo apt autoremove -y
sudo apt autoclean
sudo apt clean
echo " "

# Install APT packages.
sudo apt install -y \
git \
vrms \
exa \
mpv \
nsxiv \
neovim \
newsboat \
alacritty \
zathura \
lf \
curl \

sudo apt update
sudo apt upgrade
echo " "

# Linking up dotfiles.
cd ~ || exit
git clone --depth 1 https://github.com/Mvcvalli/.dotfiles.git
rm -rf ~/.config
mv ~/.dotfiles/.config ~
mv ~/.dotfiles/.zshenv ~
mv ~/.dotfiles/.newsboat ~
mv ~/.dotfiles/.gitconfig ~
cd ~ || exit
echo " "

# Installing vim-plug (for nvim).
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
echo " "

# Install nvim plugins
nvim -es -u init.vim -i NONE -c "PlugInstall" -c "qa"
echo " "

# Changing shell to zsh
sudo apt install zsh
sudo chsh -s $(which zsh)
zsh
echo " "

# Installing zap (zsh plugin manger)
zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1
echo " "

echo "Install complete!"
echo "Please restart your computer now"
