#!/bin/sh

# Update
sudo apt-get update -y
echo ''

# Upgrade
sudo apt-get upgrade -y
echo ''

# Distribution Upgrade
    sudo apt-get dist-upgrade -y
echo ''

# Auto remove
    sudo apt-get remove -y
    sudo apt-get autoremove -y
echo ''

# Auto clean
    sudo apt-get clean -y
    sudo apt-get autoclean -y
echo ''

# Delete Empty Files and Directories.
    find . -type d -empty -print -delete -o -type f -empty -print -delete
echo ' '

# Cleanup of ~/.config and ~/
    rm -rf ~/.config/zsh/.zsh_history
    rm -rf ~/.config/mpv/watch_later
    rm -rf ~/.pki
echo ' '

# Pulling down any new dotfiles.
    cd ~/personal/.dotfiles
    git pull
    cd ~
echo ' '

# Updating Neovim plugins
    nvim -es -u init.vim -i NONE -c "PlugClean" -c "qa"
    nvim -es -u init.vim -i NONE -c "PlugUpdate" -c "qa"
echo ' '
