#!/bin/sh

echo "An internet connection is required in order for this script to work."
echo "Before running, ensure this script is in the home directory"
echo "Before running, ensure git and xdg-user-dirs is installed."
echo " "

sudo pacman --noconfirm -Syu
sudo pacman --noconfirm -S git xdg-user-dirs
cd ~ || exit
echo " "

echo "Press [ENTER] key when ready to continue"
read y
echo " "

# Set up YAY (AUR Helper)
sudo pacman --noconfirm -S base-devel
cd ~/.config || exit
git clone https://aur.archlinux.org/yay.git
cd yay || exit
makepkg -si
cd ~ || exit
echo " "

# xdg-user-dirs
mkdir ~/personal/dox
mkdir ~/personal/dl
mkdir ~/personal/pix
mkdir ~/personal/vid

xdg-user-dirs-update --set DESKTOP ~
xdg-user-dirs-update --set DOCUMENTS ~/personal/dox
xdg-user-dirs-update --set DOWNLOAD ~/personal/dl
xdg-user-dirs-update --set MUSIC ~
xdg-user-dirs-update --set PICTURES ~/personal/pix
xdg-user-dirs-update --set PUBLIC ~
xdg-user-dirs-update --set TEMPLATES ~
xdg-user-dirs-update --set VIDEOS ~/personal/vid

xdg-user-dirs-update
xdg-user-dirs-update --force
xdg-user-dirs-gtk-update
xdg-user-dirs-gtk-update --force

rm -rf Desktop Documents Downloads Music Pictures Public Templates Videos
echo " "

# Linking up dotfiles.
rm -rf .config
cd personal || exit
git clone --depth 1 https://github.com/Mvcvalli/.dotfiles.git
sudo ln -s ~/personal/.dotfiles/.config ~
sudo ln -s ~/personal/.dotfiles/.newsboat ~
sudo ln -s ~/personal/.dotfiles/.zshenv ~
sudo ln -s ~/personal/.dotfiles/.gitconfig
echo " "

# Installing packages
pacman=(
alacritty
neovim
mpv
exa
zsh
zathura
zathura-pdf-mupdf
noto-fonts
noto-fonts-emoji
ttc-iosevka
)

yay=(
newsboat-git
sxiv
)

sudo pacman --noconfirm -S ${pacman[@]}
yay -S ${yay[@]}
echo " "

# Installng LibreWolf
cd ~/.config || exit
git clone https://aur.archlinux.org/librewolf.git
cd librewolf || exit
makepkg -si

# Neovim

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
echo " "

# Installing Neovim Plugins
nvim -es -u init.vim -i NONE -c "PlugInstall" -c "qa"
echo " "

# Changing shell to zsh
sudo chsh -s $(which zsh)
zsh
echo " "

# Installing zap (zsh plugin manger)
zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1
echo " "

echo "Install complete!"
echo "Please restart your computer now"
